namespace NaturalLanguageProcess
{
    public class CharacterPropertyCollection
    {
        private Dictionary<CharacterPropertyType, List<string>> characterPropertyMap;

        public Dictionary<CharacterPropertyType, List<string>> CharacterPropertyMap => this.characterPropertyMap;

        public CharacterPropertyCollection()
        {
            this.Initialize();
        }

        private void Initialize()
        {
            this.characterPropertyMap = new Dictionary<CharacterPropertyType, List<string>>()
            {
                { CharacterPropertyType.Skill, new List<string>() {
                        "Swordsmanship",
                        "Archery",
                        "Spellcasting",
                        "Potion brewing",
                        "Stealth",
                        "Piloting spacecraft",
                        "Hacking",
                        "Diplomacy",
                        "Historical research",
                        "Survival techniques",
                        "Mechanical repair",
                        "Animal taming",
                        "Musical talent",
                        "Artistic ability",
                        "Inventiveness",
                        "Medical knowledge",
                        "Elemental control",
                        "Telepathy",
                        "Precognition",
                        "Herbalism",
                        "Blacksmithing",
                        "Negotiation",
                        "Espionage",
                        "Cybernetic enhancements",
                        "Quantum engineering",
                        "Astro-navigation",
                        "Runic magic",
                        "Dimensional travel",
                        "Equestrianism",
                        "Acrobatics",
                        "Psychokinesis",
                        "Chronomancy"
                    }
                },
                { CharacterPropertyType.MentalState, new List<string>() {
                        "Curiosity",
                        "Ambition",
                        "Fearlessness",
                        "Paranoia",
                        "Optimism",
                        "Pessimism",
                        "Compassion",
                        "Ruthlessness",
                        "Loyalty",
                        "Betrayal",
                        "Love",
                        "Hate",
                        "Hope",
                        "Despair",
                        "Confidence",
                        "Insecurity",
                        "Wanderlust",
                        "Vengeance",
                        "Enlightenment",
                        "Nostalgia",
                        "Greed",
                        "Altruism",
                        "Curiosity",
                        "Melancholy",
                        "Euphoria",
                        "Resentment",
                        "Admiration",
                        "Contempt",
                        "Awe",
                        "Boredom",
                        "Ecstasy",
                        "Anxiety"
                    }
                },
                { CharacterPropertyType.Role, new List<string>() {
                        "Knight",
                        "Wizard",
                        "Rogue",
                        "Priestess",
                        "Alien",
                        "Time Traveler",
                        "Spy",
                        "Monarch",
                        "Rebel Leader",
                        "Pirate",
                        "Scientist",
                        "Detective",
                        "Assassin",
                        "Healer",
                        "Merchant",
                        "Diplomat",
                        "Sorcerer",
                        "Bard",
                        "Paladin",
                        "Necromancer",
                        "Archaeologist",
                        "Cyborg",
                        "Mutant",
                        "Empath",
                        "Historian",
                        "Gladiator",
                        "Shaman",
                        "Witch",
                        "Bounty Hunter",
                        "Explorer",
                        "Prophet",
                        "Rebel Spy"
                    }
                },
                { CharacterPropertyType.Name, new List<string>() {
                        "Aelar",
                        "Mirabel",
                        "Zephyr",
                        "Eldric",
                        "Lysandra",
                        "Thane",
                        "Cassius",
                        "Octavia",
                        "Seraphina",
                        "Gaius",
                        "Aurelia",
                        "Leander",
                        "Drusilla",
                        "Remus",
                        "Isolde",
                        "Fenrir",
                        "Kaelen",
                        "Niamh",
                        "Orion",
                        "Juno",
                        "Brontë",
                        "Cyrus",
                        "Delphine",
                        "Ezekiel",
                        "Freya",
                        "Galen",
                        "Hestia",
                        "Icarus",
                        "Jorah",
                        "Kira",
                        "Lorien",
                        "Maeve",
                        "Thalion",
                        "Ariwyn",
                        "Eirlys",
                        "Raelar",
                        "Ysolde",
                        "Vanth",
                        "Serilda",
                        "Draven",
                        "Fenella",
                        "Gavriel",
                        "Halia",
                        "Ivar",
                        "Jareth",
                        "Kerensa",
                        "Lior",
                        "Mirelle",
                        "Neriah",
                        "Ophira",
                        "Perrin",
                        "Quintessa",
                        "Rhoswen",
                        "Sariel",
                        "Tavion",
                        "Ulyssia",
                        "Varek",
                        "Wystan",
                        "Xylander",
                        "Yaroslav",
                        "Zephyra",
                        "Calix",
                        "Nova",
                        "Orion",
                        "Zenon",
                        "Lyra",
                        "Cassian",
                        "Talos",
                        "Seren",
                        "Vega",
                        "Axton",
                        "Nyx",
                        "Eos",
                        "Dax",
                        "Riven",
                        "Quorra",
                        "Helios",
                        "Iridia",
                        "Jax",
                        "Kato",
                        "Lunara",
                        "Mako",
                        "Nero",
                        "Ora",
                        "Pax",
                        "Qinn",
                        "Ryker",
                        "Syla",
                        "Tyr",
                        "Urania",
                        "Velox",
                        "Wren",
                        "Xeno",
                        "Yale",
                        "Zorin",
                        "Aurelian",
                        "Beatrix",
                        "Cornelius",
                        "Dorothea",
                        "Emilian",
                        "Faustina",
                        "Gaius",
                        "Hadrian",
                        "Isolde",
                        "Jocasta",
                        "Kassia",
                        "Leander",
                        "Myron",
                        "Nerissa",
                        "Octavia",
                        "Philo",
                        "Quintus",
                        "Rosalind",
                        "Severus",
                        "Theodora",
                        "Ulysses",
                        "Valeria",
                        "Wilfred",
                        "Xanthe",
                        "Yolanda",
                        "Zeno"
                    }
                },
            };
        }
    }
}
