namespace NaturalLanguageProcess
{
    public enum MoodType
    {
        None = 0,
        Content,
        Curious,
        Entrepreneurial,
        Patriotic,
        Celebratory,
        Happy,
        Sad,
        Angry,
        Anxious,
        Relaxed,
        Excited,
        Bored,
        Hopeful,
        Frustrated,
        Inspired,
        Nostalgic,
        Confident,
        Fearful,
        Optimistic,
        Pessimistic,
        Calm,
        Energetic,
        Melancholic,
        Grateful,
        Overwhelmed,
        Relieved,
        Surprised,
        Amused,
        Indifferent,
        Motivated,
        Disappointed,
        Sympathetic,
        Empathetic,
        Reflective,
        Restless,
        Peaceful,
        Other // Allows for extension beyond predefined moods
    }
}
